### ISSUE TITLE
Cannot run npm run build on node v14

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/dcat-ap-viewer#186]
This happens on Node v14.2.0, npm 6.14.5, Ubuntu 19.10

Works with node v13.14.

```

klimek@xrg13:~/dcat-ap-viewer$ npm run build -- -env.configurationFile=configuration.yaml

> dcat-viewer@1.0.0-alpha.0 build /home/klimek/dcat-ap-viewer
> cross-env NODE_ENV=production webpack --config build/webpack.production.js "-env.configurationFile=configuration.yaml"

Using configuration:  /home/klimek/dcat-ap-viewer/configuration.yaml
Hash: 581d3b5a6de35d299293
Version: webpack 4.42.0
Time: 1291ms
Built at: 05/06/2020 5:53:28 PM
 1 asset
Entrypoint main = assets/bundle.c31de222591c461aead6.js
[0] multi ./client/index.jsx 28 bytes {0} [built]
[1] ./client/index.jsx 4.58 KiB {0} [built] [failed] [1 error]

ERROR in ./client/index.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/klimek/dcat-ap-viewer/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/klimek/dcat-ap-viewer/node_modules/@babel/preset-env/lib/index.js
- /home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/files/plugins.js
- /home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/files/index.js
- /home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/index.js
- /home/klimek/dcat-ap-viewer/node_modules/babel-loader/lib/index.js
- /home/klimek/dcat-ap-viewer/node_modules/loader-runner/lib/loadLoader.js
- /home/klimek/dcat-ap-viewer/node_modules/loader-runner/lib/LoaderRunner.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack/lib/NormalModule.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack/lib/NormalModuleFactory.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack/lib/Compiler.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack/lib/webpack.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack-cli/bin/utils/validate-options.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack-cli/bin/cli.js
- /home/klimek/dcat-ap-viewer/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (/home/klimek/dcat-ap-viewer/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/klimek/dcat-ap-viewer/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (/home/klimek/dcat-ap-viewer/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (/home/klimek/dcat-ap-viewer/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/klimek/dcat-ap-viewer/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (/home/klimek/dcat-ap-viewer/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (/home/klimek/dcat-ap-viewer/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at Generator.next (<anonymous>)
    at buildRootChain (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/config-chain.js:90:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/partial.js:95:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at Function.<anonymous> (/home/klimek/dcat-ap-viewer/node_modules/@babel/core/lib/config/partial.js:120:25)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/klimek/dcat-ap-viewer/node_modules/gensync/index.js:244:28)
 @ multi ./client/index.jsx main[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./profile/nkod/index.html 1.28 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! dcat-viewer@1.0.0-alpha.0 build: `cross-env NODE_ENV=production webpack --config build/webpack.production.js "-env.configurationFile=configuration.yaml"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the dcat-viewer@1.0.0-alpha.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/klimek/.npm/_logs/2020-05-06T15_53_28_649Z-debug.log
```

**Comment by jakubklimek** [comment]
Not happening anymore one Ubuntu 20.04 and node 14.3. Also, in the example, there is an erroneous config file parameter.
